
[2025-02-06 11:18:41] INFO - caller_builder.py: 302

Preparing docker env for execution test...

[2025-02-06 11:18:41] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy/.git/objects/pack'
Attempting directory removal again...

[2025-02-06 11:18:41] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy/.git/objects'
Attempting directory removal again...

[2025-02-06 11:18:41] INFO - caller_builder.py: 302

Preparing docker env for execution test...

[2025-02-06 11:18:41] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/.git/objects/pack'
Attempting directory removal again...

[2025-02-06 11:18:41] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/.git/objects'
Attempting directory removal again...

[2025-02-06 11:18:44] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy/.git'
Attempting directory removal again...

[2025-02-06 11:18:44] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller15/15_spacy'
Attempting directory removal again...

[2025-02-06 11:18:44] INFO - caller_builder.py: 136

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/caller15/'

[2025-02-06 11:18:44] INFO - builder.py: 176

Checking if Docker image 'xuehang/15_spacy' exists...

Docker image 'xuehang/15_spacy' already exists with ID: 059492a93bd6

[2025-02-06 11:18:44] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/`

[2025-02-06 11:18:44] INFO - handler.py: 42

Container xuehang_15_spacy_3.11__Thu__Feb____6__11_18_44__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:18:45] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/.git'
Attempting directory removal again...

[2025-02-06 11:18:45] WARNING - caller_builder.py: 132

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow'
Attempting directory removal again...

[2025-02-06 11:18:45] INFO - caller_builder.py: 136

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/caller21/'

[2025-02-06 11:18:45] INFO - builder.py: 176

Checking if Docker image 'xuehang/21_mlflow' exists...

Docker image 'xuehang/21_mlflow' already exists with ID: 73f308f5c08c

[2025-02-06 11:18:45] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/caller21/test_repo/`

[2025-02-06 11:18:46] INFO - handler.py: 42

Container xuehang_21_mlflow_3.11__Thu__Feb____6__11_18_45__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:18:52] INFO - tester.py: 92

Execution succeeded!
Container output: 
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pillow
  Building editable for pillow (pyproject.toml): started
  Building editable for pillow (pyproject.toml): finished with status 'done'
  Created wheel for pillow: filename=pillow-11.0.0.dev0-0.editable-cp311-cp311-linux_x86_64.whl size=4639 sha256=7a8bd3af207e8be0f1a2ef9ef8c572b73a5585b99cbad6c9697b3aaeb7c9d048
  Stored in directory: /tmp/pip-ephem-wheel-cache-qfligt0a/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built pillow
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: pillow 11.0.0.dev0
    Uninstalling pillow-11.0.0.dev0:
      Successfully uninstalled pillow-11.0.0.dev0
Successfully installed pillow-11.0.0.dev0
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
--------------------------------------------------------------------
Pillow 11.0.0.dev0
Python 3.11.9 (main, Sep  5 2024, 00:16:19) [GCC 12.2.0]
--------------------------------------------------------------------
Python executable is /workspace/test_venv/bin/python
Environment Python files loaded from /workspace/test_venv
System Python files loaded from /usr/local
--------------------------------------------------------------------
Python Pillow modules loaded from /workspace/test_repo/src/PIL
Binary Pillow modules loaded from /workspace/test_repo/src/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 11.0.0.dev0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.12.1
--- LITTLECMS2 support ok, loaded 2.14
--- WEBP support ok, loaded 1.2.4
--- JPEG support ok, compiled for libjpeg-turbo 2.1.5
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.0
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.13
--- LIBTIFF support ok, loaded 4.5.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------

rootdir: /workspace/test_repo
configfile: pyproject.toml
plugins: asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
[1mcollecting ... [0mcollected 25 items

Tests/test_imagefile.py::TestImageFile::test_parser [32mPASSED[0m[32m               [  4%][0m
Tests/test_imagefile.py::TestImageFile::test_ico [32mPASSED[0m[32m                  [  8%][0m
Tests/test_imagefile.py::TestImageFile::test_incremental_webp [32mPASSED[0m[32m     [ 12%][0m
Tests/test_imagefile.py::TestImageFile::test_safeblock [32mPASSED[0m[32m            [ 16%][0m
Tests/test_imagefile.py::TestImageFile::test_raise_oserror [32mPASSED[0m[32m        [ 20%][0m
Tests/test_imagefile.py::TestImageFile::test_raise_typeerror [32mPASSED[0m[32m      [ 24%][0m
Tests/test_imagefile.py::TestImageFile::test_negative_stride [32mPASSED[0m[32m      [ 28%][0m
Tests/test_imagefile.py::TestImageFile::test_no_format [32mPASSED[0m[32m            [ 32%][0m
Tests/test_imagefile.py::TestImageFile::test_oserror [32mPASSED[0m[32m              [ 36%][0m
Tests/test_imagefile.py::TestImageFile::test_truncated [32mPASSED[0m[32m            [ 40%][0m
Tests/test_imagefile.py::TestImageFile::test_truncated_with_errors [32mPASSED[0m[32m [ 44%][0m
Tests/test_imagefile.py::TestImageFile::test_truncated_without_errors [32mPASSED[0m[32m [ 48%][0m
Tests/test_imagefile.py::TestImageFile::test_broken_datastream_with_errors [32mPASSED[0m[32m [ 52%][0m
Tests/test_imagefile.py::TestImageFile::test_broken_datastream_without_errors [32mPASSED[0m[32m [ 56%][0m
Tests/test_imagefile.py::TestPyDecoder::test_setimage [32mPASSED[0m[32m             [ 60%][0m
Tests/test_imagefile.py::TestPyDecoder::test_extents_none [32mPASSED[0m[32m         [ 64%][0m
Tests/test_imagefile.py::TestPyDecoder::test_negsize [32mPASSED[0m[32m              [ 68%][0m
Tests/test_imagefile.py::TestPyDecoder::test_oversize [32mPASSED[0m[32m             [ 72%][0m
Tests/test_imagefile.py::TestPyDecoder::test_decode [32mPASSED[0m[32m               [ 76%][0m
Tests/test_imagefile.py::TestPyEncoder::test_setimage [32mPASSED[0m[32m             [ 80%][0m
Tests/test_imagefile.py::TestPyEncoder::test_extents_none [32mPASSED[0m[32m         [ 84%][0m
Tests/test_imagefile.py::TestPyEncoder::test_negsize [32mPASSED[0m[32m              [ 88%][0m
Tests/test_imagefile.py::TestPyEncoder::test_oversize [32mPASSED[0m[32m             [ 92%][0m
Tests/test_imagefile.py::TestPyEncoder::test_encode [32mPASSED[0m[32m               [ 96%][0m
Tests/test_imagefile.py::TestPyEncoder::test_zero_height [32mPASSED[0m[32m          [100%][0m

[32m============================== [32m[1m25 passed[0m[32m in 0.41s[0m[32m ==============================[0m


[2025-02-06 11:18:52] INFO - tester.py: 168

[2025-02-06 11:18:52] INFO - tester.py: 257

{'total': 25, 'passed': 25, 'xpassed': 0, 'failed': 0, 'xfailed': 0, 'deselected': 0, 'skipped': 0, 'warning': 0, 'error': 0}

[2025-02-06 11:18:52] INFO - tester.py: 436

Number of test evals in current unit test: 25

[2025-02-06 11:18:52] INFO - tester.py: 66

Stopping and removing container 'xuehang_16_pillow_container__is_win32__Thu_Feb__6_11_18_27_2025'...

Successfully removed container 'xuehang_16_pillow_container__is_win32__Thu_Feb__6_11_18_27_2025'

[2025-02-06 11:18:53] INFO - exetest.py: 155

Successfully removed target directory at `/shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/`

[2025-02-06 11:18:53] INFO - tester.py: 79

Removing temporary directory used for repository at '/shared/nas2/xuehangg/syncbench_build/code/callee16/test_repo/'

[2025-02-06 11:18:53] INFO - callee_builder.py: 491

[Execution Test for 'original_code + new_context'] Passed


[2025-02-06 11:18:53] INFO - callee_builder.py: 741


=========================  Function/method filtering 29/34: [test_imagefile.py] -> [helper.py] -> [is_pypy]  =========================

[2025-02-06 11:18:53] WARNING - callee_builder.py: 393

An error occurred when tracing commit history: /shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow
Attemptaining again...

[2025-02-06 11:18:53] INFO - builder.py: 176

Checking if Docker image 'xuehang/16_pillow' exists...

Docker image 'xuehang/16_pillow' already exists with ID: fc29e8ee0f09

[2025-02-06 11:18:53] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/`.

Removing existing repo and re-cloning...

[2025-02-06 11:18:53] WARNING - exetest.py: 144

Failed to remove file /shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack/.nfs000000000c52576b00014948: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack/.nfs000000000c52576b00014948'
Attempting to remove file /shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack/.nfs000000000c52576b00014948 again...

[2025-02-06 11:18:53] WARNING - exetest.py: 144

Failed to remove file /shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack/.nfs000000000c52675c00014947: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack/.nfs000000000c52675c00014947'
Attempting to remove file /shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack/.nfs000000000c52675c00014947 again...

[2025-02-06 11:18:53] WARNING - exetest.py: 151

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack'
Attempting to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects/pack` again...

[2025-02-06 11:18:53] WARNING - exetest.py: 151

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects'
Attempting to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git/objects` again...

[2025-02-06 11:18:53] WARNING - exetest.py: 151

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git'
Attempting to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/.git` again...

[2025-02-06 11:18:53] INFO - exetest.py: 155

Successfully removed target directory at `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/`

[2025-02-06 11:18:53] INFO - handler.py: 22

The local path '/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/' already exists.

[2025-02-06 11:18:54] INFO - handler.py: 42

Container xuehang_16_pillow_3.11__Thu__Feb____6__11_18_53__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:18:54] INFO - callee_builder.py: 297

Preparing docker env for execution test...

[2025-02-06 11:18:54] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack'
Attempting directory removal again...

[2025-02-06 11:18:54] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects'
Attempting directory removal again...

[2025-02-06 11:18:55] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git'
Attempting directory removal again...

[2025-02-06 11:18:55] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest'
Attempting directory removal again...

[2025-02-06 11:18:55] INFO - callee_builder.py: 134

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/'

[2025-02-06 11:18:55] INFO - builder.py: 176

Checking if Docker image 'xuehang/7_pytest' exists...

Docker image 'xuehang/7_pytest' already exists with ID: 2ad0b81aebdc

[2025-02-06 11:18:55] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:18:55] INFO - handler.py: 42

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_18_55__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-06 11:18:59] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/

[2025-02-06 11:18:59] INFO - handler.py: 77

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_18_55__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:18:59] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:18:59] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `cleanup_dead_symlinks` in the context_code.

[2025-02-06 11:18:59] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py' already exists.

[2025-02-06 11:18:59] INFO - callee_builder.py: 305

Using docker image with ID: 2ad0b81aebdc

[2025-02-06 11:18:59] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`.

Skipping repo clone...

[2025-02-06 11:18:59] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `cleanup_dead_symlinks` in the context_code.

[2025-02-06 11:18:59] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py

[2025-02-06 11:18:59] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pathlib.py'

[2025-02-06 11:18:59] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/testing/test_pathlib.py` in Docker container `xuehang_7_pytest_container_cleanup_dead_symlinks_Thu_Feb__6_11_18_59_2025`...

[2025-02-06 11:19:04] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/

[2025-02-06 11:19:04] INFO - handler.py: 77

Container xuehang_15_spacy_3.11__Thu__Feb____6__11_18_44__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:19:04] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/`

[2025-02-06 11:19:04] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `test_doc_array_attr_of_token` in the context_code.

[2025-02-06 11:19:04] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/spacy/tests/doc/test_array.py' already exists.

[2025-02-06 11:19:04] INFO - caller_builder.py: 310

Using docker image with ID: 059492a93bd6

[2025-02-06 11:19:04] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/`.

Skipping repo clone...

[2025-02-06 11:19:04] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `test_doc_array_attr_of_token` in the context_code.

[2025-02-06 11:19:04] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/spacy/tests/doc/test_array.py

[2025-02-06 11:19:04] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/caller15/test_repo/spacy/tests/doc/test_array.py'

[2025-02-06 11:19:04] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/spacy/tests/doc/test_array.py` in Docker container `xuehang_15_spacy_container__test_doc_array_attr_of_token__Thu_Feb__6_11_19_04_2025`...

[2025-02-06 11:19:05] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/

[2025-02-06 11:19:05] INFO - handler.py: 77

Container xuehang_16_pillow_3.11__Thu__Feb____6__11_18_53__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-06 11:19:05] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee16/16_pillow/`

Update: Commit tracing success!

[2025-02-06 11:19:06] INFO - tester.py: 92

Execution succeeded!
Container output: 
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: iniconfig in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (2.0.0)
Requirement already satisfied: packaging in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (24.1)
Requirement already satisfied: pluggy<2,>=1.5 in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (1.5.0)
Building wheels for collected packages: pytest
  Building editable for pytest (pyproject.toml): started
  Building editable for pytest (pyproject.toml): finished with status 'done'
  Created wheel for pytest: filename=pytest-8.4.0.dev64+g72c682ff9.d20250206-0.editable-py3-none-any.whl size=9450 sha256=9cda8b694f1b8b324337ddf6c118cd663e332a6530c503e077aeb16dd485424a
  Stored in directory: /tmp/pip-ephem-wheel-cache-eqh_6jpx/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built pytest
Installing collected packages: pytest
  Attempting uninstall: pytest
    Found existing installation: pytest 8.4.0.dev64+g72c682ff9
    Uninstalling pytest-8.4.0.dev64+g72c682ff9:
      Successfully uninstalled pytest-8.4.0.dev64+g72c682ff9
Successfully installed pytest-8.4.0.dev64+g72c682ff9.d20250206
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.4.0.dev64+g72c682ff9.d20250206, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
rootdir: /workspace/test_repo
configfile: pyproject.toml
plugins: asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collecting ... collected 97 items

testing/test_pathlib.py::TestFNMatcherPort::test_matching[*.py-foo.py] PASSED [  1%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[*.py-bar/foo.py] PASSED [  2%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[test_*.py-foo/test_foo.py] PASSED [  3%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/*.py-tests/foo.py] PASSED [  4%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[/c/*.py-/c/foo.py] PASSED [  5%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[/c/foo/*.py-/c/foo/foo.py] PASSED [  6%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/test*.py-tests/foo/test_foo.py] PASSED [  7%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/doc/test*.py-tests/foo/bar/doc/test_foo.py] PASSED [  8%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching[tests/**/doc/**/test*.py-tests/foo/doc/bar/test_foo.py] PASSED [  9%]
testing/test_pathlib.py::TestFNMatcherPort::test_matching_abspath PASSED [ 10%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[*.py-foo.pyc] PASSED [ 11%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[*.py-foo/foo.pyc] PASSED [ 12%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/*.py-foo/foo.py] PASSED [ 13%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[/c/*.py-/d/foo.py] PASSED [ 14%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[/c/foo/*.py-/d/foo/foo.py] PASSED [ 15%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/test*.py-tests/foo.py] PASSED [ 16%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/test*.py-foo/test_foo.py] PASSED [ 17%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/doc/test*.py-tests/foo/bar/doc/foo.py] PASSED [ 18%]
testing/test_pathlib.py::TestFNMatcherPort::test_not_matching[tests/**/doc/test*.py-tests/foo/bar/test_foo.py] PASSED [ 19%]
testing/test_pathlib.py::TestImportPath::test_smoke_test[True] PASSED    [ 20%]
testing/test_pathlib.py::TestImportPath::test_smoke_test[False] PASSED   [ 21%]
testing/test_pathlib.py::TestImportPath::test_import_path_missing_file[True] PASSED [ 22%]
testing/test_pathlib.py::TestImportPath::test_import_path_missing_file[False] PASSED [ 23%]
testing/test_pathlib.py::TestImportPath::test_renamed_dir_creates_mismatch[True] PASSED [ 24%]
testing/test_pathlib.py::TestImportPath::test_renamed_dir_creates_mismatch[False] PASSED [ 25%]
testing/test_pathlib.py::TestImportPath::test_messy_name[True] PASSED    [ 26%]
testing/test_pathlib.py::TestImportPath::test_messy_name[False] PASSED   [ 27%]
testing/test_pathlib.py::TestImportPath::test_dir[True] PASSED           [ 28%]
testing/test_pathlib.py::TestImportPath::test_dir[False] PASSED          [ 29%]
testing/test_pathlib.py::TestImportPath::test_a[True] PASSED             [ 30%]
testing/test_pathlib.py::TestImportPath::test_a[False] PASSED            [ 31%]
testing/test_pathlib.py::TestImportPath::test_b[True] PASSED             [ 32%]
testing/test_pathlib.py::TestImportPath::test_b[False] PASSED            [ 34%]
testing/test_pathlib.py::TestImportPath::test_c[True] PASSED             [ 35%]
testing/test_pathlib.py::TestImportPath::test_c[False] PASSED            [ 36%]
testing/test_pathlib.py::TestImportPath::test_d[True] PASSED             [ 37%]
testing/test_pathlib.py::TestImportPath::test_d[False] PASSED            [ 38%]
testing/test_pathlib.py::TestImportPath::test_import_after[True] PASSED  [ 39%]
testing/test_pathlib.py::TestImportPath::test_import_after[False] PASSED [ 40%]
testing/test_pathlib.py::TestImportPath::test_check_filepath_consistency[True] PASSED [ 41%]
testing/test_pathlib.py::TestImportPath::test_check_filepath_consistency[False] PASSED [ 42%]
testing/test_pathlib.py::TestImportPath::test_ensuresyspath_append[True] PASSED [ 43%]
testing/test_pathlib.py::TestImportPath::test_ensuresyspath_append[False] PASSED [ 44%]
testing/test_pathlib.py::TestImportPath::test_invalid_path[True] PASSED  [ 45%]
testing/test_pathlib.py::TestImportPath::test_invalid_path[False] PASSED [ 46%]
testing/test_pathlib.py::TestImportPath::test_importmode_importlib[True] PASSED [ 47%]
testing/test_pathlib.py::TestImportPath::test_importmode_importlib[False] PASSED [ 48%]
testing/test_pathlib.py::TestImportPath::test_remembers_previous_imports[True] PASSED [ 49%]
testing/test_pathlib.py::TestImportPath::test_remembers_previous_imports[False] PASSED [ 50%]
testing/test_pathlib.py::TestImportPath::test_no_meta_path_found[True] PASSED [ 51%]
testing/test_pathlib.py::TestImportPath::test_no_meta_path_found[False] PASSED [ 52%]
testing/test_pathlib.py::test_resolve_package_path PASSED                [ 53%]
testing/test_pathlib.py::test_package_unimportable PASSED                [ 54%]
testing/test_pathlib.py::test_access_denied_during_cleanup PASSED        [ 55%]
testing/test_pathlib.py::test_long_path_during_cleanup PASSED            [ 56%]
testing/test_pathlib.py::test_get_extended_length_path_str PASSED        [ 57%]
testing/test_pathlib.py::test_suppress_error_removing_lock PASSED        [ 58%]
testing/test_pathlib.py::test_bestrelpath PASSED                         [ 59%]
testing/test_pathlib.py::test_commonpath PASSED                          [ 60%]
testing/test_pathlib.py::test_visit_ignores_errors PASSED                [ 61%]
testing/test_pathlib.py::test_samefile_false_negatives SKIPPED (Wind...) [ 62%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_dataclass[True] PASSED [ 63%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_dataclass[False] PASSED [ 64%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle[True] PASSED [ 65%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle[False] PASSED [ 67%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle_separate_modules[True] PASSED [ 68%]
testing/test_pathlib.py::TestImportLibMode::test_importmode_importlib_with_pickle_separate_modules[False] PASSED [ 69%]
testing/test_pathlib.py::TestImportLibMode::test_module_name_from_path PASSED [ 70%]
testing/test_pathlib.py::TestImportLibMode::test_resolve_pkg_root_and_module_name PASSED [ 71%]
testing/test_pathlib.py::TestImportLibMode::test_insert_missing_modules PASSED [ 72%]
testing/test_pathlib.py::TestImportLibMode::test_parent_contains_child_module_attribute PASSED [ 73%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_package[True] PASSED [ 74%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_package[False] PASSED [ 75%]
testing/test_pathlib.py::TestImportLibMode::test_importlib_root_is_package PASSED [ 76%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first[True] PASSED [ 77%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first[False] PASSED [ 78%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first_integration[True] PASSED [ 79%]
testing/test_pathlib.py::TestImportLibMode::test_import_using_normal_mechanism_first_integration[False] PASSED [ 80%]
testing/test_pathlib.py::TestImportLibMode::test_import_path_imports_correct_file[True] PASSED [ 81%]
testing/test_pathlib.py::TestImportLibMode::test_import_path_imports_correct_file[False] PASSED [ 82%]
testing/test_pathlib.py::test_safe_exists PASSED                         [ 83%]
testing/test_pathlib.py::test_import_sets_module_as_attribute PASSED     [ 84%]
testing/test_pathlib.py::test_import_sets_module_as_attribute_without_init_files PASSED [ 85%]
testing/test_pathlib.py::test_import_sets_module_as_attribute_regression PASSED [ 86%]
testing/test_pathlib.py::test_import_submodule_not_namespace PASSED      [ 87%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[prepend] PASSED [ 88%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[append] PASSED [ 89%]
testing/test_pathlib.py::TestNamespacePackages::test_resolve_pkg_root_and_module_name_ns_multiple_levels[importlib] PASSED [ 90%]
testing/test_pathlib.py::TestNamespacePackages::test_ns_multiple_levels_import_rewrite_assertions PASSED [ 91%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[prepend] PASSED [ 92%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[append] PASSED [ 93%]
testing/test_pathlib.py::TestNamespacePackages::test_incorrect_namespace_package[importlib] PASSED [ 94%]
testing/test_pathlib.py::TestNamespacePackages::test_detect_meta_path PASSED [ 95%]
testing/test_pathlib.py::TestNamespacePackages::test_full_ns_packages_without_init_files[True] PASSED [ 96%]
testing/test_pathlib.py::TestNamespacePackages::test_full_ns_packages_without_init_files[False] PASSED [ 97%]
testing/test_pathlib.py::test_is_importable PASSED                       [ 98%]
testing/test_pathlib.py::test_compute_module_name PASSED                 [100%]

======================== 96 passed, 1 skipped in 0.94s =========================


[2025-02-06 11:19:06] INFO - tester.py: 257

{'total': 97, 'passed': 96, 'xpassed': 0, 'failed': 0, 'xfailed': 0, 'deselected': 0, 'skipped': 1, 'warning': 0, 'error': 0}

[2025-02-06 11:19:06] INFO - tester.py: 436

Number of test evals in current unit test: 97

[2025-02-06 11:19:06] INFO - tester.py: 66

Stopping and removing container 'xuehang_7_pytest_container_cleanup_dead_symlinks_Thu_Feb__6_11_18_59_2025'...

Successfully removed container 'xuehang_7_pytest_container_cleanup_dead_symlinks_Thu_Feb__6_11_18_59_2025'

[2025-02-06 11:19:06] INFO - exetest.py: 155

Successfully removed target directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/'

[2025-02-06 11:19:06] INFO - tester.py: 79

Removing temporary directory used for repository at '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/'

[2025-02-06 11:19:06] INFO - callee_builder.py: 480

[Execution Test for 'gold_code + new_context'] Passed


[2025-02-06 11:19:06] INFO - callee_builder.py: 297

Preparing docker env for execution test...

[2025-02-06 11:19:06] WARNING - callee_builder.py: 123

Failed to remove file `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c4bbc6c0001494d`: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c4bbc6c0001494d'
Attempting file removal again...

[2025-02-06 11:19:06] WARNING - callee_builder.py: 123

Failed to remove file `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c4bbe470001494e`: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c4bbe470001494e'
Attempting file removal again...

[2025-02-06 11:19:06] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack'
Attempting directory removal again...

[2025-02-06 11:19:06] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects'
Attempting directory removal again...

[2025-02-06 11:19:06] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git'
Attempting directory removal again...

[2025-02-06 11:19:06] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest'
Attempting directory removal again...

[2025-02-06 11:19:06] INFO - callee_builder.py: 134

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/'

[2025-02-06 11:19:06] INFO - builder.py: 176

Checking if Docker image 'xuehang/7_pytest' exists...

Docker image 'xuehang/7_pytest' already exists with ID: 2ad0b81aebdc

[2025-02-06 11:19:06] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-06 11:19:07] INFO - handler.py: 42

Container xuehang_7_pytest_3.11__Thu__Feb____6__11_19_06__2025__test_repo__dockerhandler_attempt1 started successfully.
